config/routes.rb
Rails.application.routes.draw do
  # Generic Syntax
  # Verb 'path', to: 'controller#action'
  root to: 'pages#home'

  get 'about', to: 'pages#about', as: :banana
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about; end

  def home
    # Some sort of model interaction potentially
    # Load some variables
    raise
    @members = ['donnie', 'sally', 'nico', 'sheila', 'bobbo']

    if params[:member]
      @members = @members.select do |member|
        member.start_with?(params["member"].downcase)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFirstAppB803</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p>This is a footer on every page now!</p>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Our awesome About Page 🚀</h1>
<h4>The time right now is <%= Time.now %></h4>
<p>These are some cool details about our application</p>

<%= link_to "Home Link", root_path %>

app/views/pages/home.html.erb
<h1>This is our super cool home page 🏡</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem odit culpa at tempora illum sed, suscipit inventore commodi officia eos excepturi cumque nemo, eum quasi, libero alias numquam magni rerum.</p>

<form action="/" method="get">
  <input type="text" name="member" placeholder="<%= params[:member] %>">
  <input type="submit">
</form>

<ul>
  <% @members.each do |person| %>
      <li><%= person.capitalize %></li>
  <% end %>
</ul>

<%= link_to "About Link", banana_path %>